"""Load host-authored Conjecture Scenario candidates for the local UI.

Candidates are Scenario YAML (precursor to Script), usually generated by a host
author (``conjecture candidates author`` or host wrapper).

Discovery order:
  1. ``CONJECTURE_CANDIDATES_DIR`` env
  2. Walk cwd parents for ``candidates/scenarios/manifest.json``
  3. Empty list (UI shows how to generate)
"""
from __future__ import annotations

import json
import os
import re
from pathlib import Path
from typing import Any, Optional

_SAFE_ID = re.compile(r"^[A-Za-z0-9._-]{1,160}$")

# Author source → UI family (expansion vs invention)
_INVENTION_SOURCES = frozenset({"invention"})
_EXPANSION_SOURCES = frozenset({
    "sole_continue_x_foreign",
    "matrix_queue",
    "residual",
    "residual_heuristic",
    "example",
})
_INCIDENT_SOURCES = frozenset({"host_incident"})


def source_family(source: str | None) -> str:
    """Map author source to a console family bucket."""
    s = (source or "").strip()
    if s in _INVENTION_SOURCES:
        return "invention"
    if s in _INCIDENT_SOURCES:
        return "incident"
    if s in _EXPANSION_SOURCES or s.startswith("matrix") or s.startswith("sole_"):
        return "expansion"
    return "other"


def failure_class_from_row(
    row: dict[str, Any],
    *,
    scenario_yaml_scope: Any = None,
) -> str:
    """Best-effort failure-mode class (taxonomy id), not the scenario id."""
    for key in ("failure_class", "failure_mode", "mode_slug", "registry_id"):
        v = row.get(key)
        if v:
            return str(v).strip()
    path_id = str(row.get("path_id") or "")
    # invent.exclusive… / matrix.owner_steal… / residual…
    parts = [p for p in path_id.split(".") if p]
    if len(parts) >= 2 and parts[0] in ("matrix", "residual", "incident", "invent"):
        # matrix.hollow_open… → hollow_open; invent… often packs class in scope
        if parts[0] == "matrix" and len(parts) >= 2:
            return parts[1]
        if parts[0] == "residual" and len(parts) >= 2:
            return parts[1]
        if parts[0] == "incident" and len(parts) >= 2:
            return parts[1]
    if isinstance(scenario_yaml_scope, dict):
        for line in scenario_yaml_scope.get("in_scope") or []:
            s = str(line)
            if s.startswith("failure_class="):
                return s.split("=", 1)[-1].strip()
    return ""


def resolve_candidates_dir(
    explicit: Optional[str | Path] = None,
) -> Optional[Path]:
    if explicit is not None:
        p = Path(explicit)
        return p if p.is_dir() else None
    env = (os.environ.get("CONJECTURE_CANDIDATES_DIR") or "").strip()
    if env:
        p = Path(env).expanduser()
        if p.is_dir():
            return p
    # Portable layout: any host may put authored scenarios under candidates/scenarios
    cwd = Path.cwd().resolve()
    for base in [cwd, *cwd.parents]:
        p = base / "candidates" / "scenarios"
        if p.is_dir() and (p / "manifest.json").is_file():
            return p
        if base.parent == base:
            break
    return None


def _load_manifest(cdir: Path) -> dict[str, Any]:
    mp = cdir / "manifest.json"
    if not mp.is_file():
        return {"scenarios": [], "generator": None, "role": None}
    try:
        data = json.loads(mp.read_text(encoding="utf-8"))
        return data if isinstance(data, dict) else {"scenarios": []}
    except Exception:  # noqa: BLE001
        return {"scenarios": [], "error": "manifest_unreadable"}


def list_candidates(
    *,
    candidates_dir: Optional[str | Path] = None,
    seal: Optional[str] = None,
    priority: Optional[str] = None,
    source: Optional[str] = None,
    family: Optional[str] = None,
    limit: int = 200,
    q: Optional[str] = None,
) -> dict[str, Any]:
    """Return list payload for GET /api/candidates.

    Each row is a **candidate scenario** (one trajectory / path), not a failure-mode
    class. Many scenarios may share one ``failure_class`` (taxonomy id).
    """
    cdir = resolve_candidates_dir(candidates_dir)
    if cdir is None:
        return {
            "ok": True,
            "dir": None,
            "count": 0,
            "scenarios": [],
            "groups": {},
            "hint": (
                "No candidate Scenario dir found. Run "
                "`conjecture candidates author --example --out DIR` "
                "(or your host author), then set "
                "CONJECTURE_CANDIDATES_DIR=DIR and re-open this console. "
                "Use `--invent-llm` for invention runs; open invent_run.json "
                "in that dir to see what was generated."
            ),
            "role": "Scenario precursor to Script",
            "taxonomy_note": (
                "Failure mode = class/category (e.g. owner_steal). "
                "Candidate scenario = one multi-turn trajectory that may map to that class."
            ),
        }
    man = _load_manifest(cdir)
    rows = list(man.get("scenarios") or [])
    if not isinstance(rows, list):
        rows = []

    # Enrich rows with family + failure_class for the console
    enriched: list[dict[str, Any]] = []
    for r in rows:
        if not isinstance(r, dict):
            continue
        row = dict(r)
        src = str(row.get("source") or "")
        row["family"] = source_family(src)
        if not row.get("failure_class"):
            row["failure_class"] = failure_class_from_row(row)
        enriched.append(row)

    def _ok(row: dict[str, Any]) -> bool:
        if seal and str(row.get("seal_status") or "") != seal:
            return False
        if priority and str(row.get("priority") or "") != priority:
            return False
        if source:
            # Allow family alias: source=expansion|invention
            if source in ("expansion", "invention", "incident", "other"):
                if row.get("family") != source:
                    return False
            elif str(row.get("source") or "") != source:
                return False
        if family and str(row.get("family") or "") != family:
            return False
        if q:
            blob = " ".join(
                str(row.get(k) or "")
                for k in (
                    "scenario_id",
                    "path_id",
                    "source",
                    "family",
                    "failure_class",
                    "seal_status",
                )
            ).lower()
            if q.lower() not in blob:
                return False
        return True

    filtered = [r for r in enriched if _ok(r)]
    # Prefer open/partial high first (manifest may already be sorted)
    pri = {"high": 0, "medium": 1, "low": 2}
    seal_r = {"open": 0, "partial": 1, "sealed": 2, "regression_check": 3}
    fam_r = {"invention": 0, "expansion": 1, "incident": 2, "other": 3}

    def _key(r: dict[str, Any]) -> tuple:
        return (
            fam_r.get(str(r.get("family") or ""), 9),
            pri.get(str(r.get("priority") or ""), 9),
            seal_r.get(str(r.get("seal_status") or ""), 9),
            str(r.get("failure_class") or ""),
            str(r.get("scenario_id") or ""),
        )

    filtered = sorted(filtered, key=_key)[: max(0, int(limit))]
    by_seal: dict[str, int] = {}
    by_src: dict[str, int] = {}
    by_family: dict[str, int] = {}
    by_failure_class: dict[str, int] = {}
    for r in enriched:
        s = str(r.get("seal_status") or "?")
        by_seal[s] = by_seal.get(s, 0) + 1
        src = str(r.get("source") or "?")
        by_src[src] = by_src.get(src, 0) + 1
        fam = str(r.get("family") or "?")
        by_family[fam] = by_family.get(fam, 0) + 1
        fc = str(r.get("failure_class") or "?")
        by_failure_class[fc] = by_failure_class.get(fc, 0) + 1

    groups: dict[str, list[dict[str, Any]]] = {
        "invention": [],
        "expansion": [],
        "incident": [],
        "other": [],
    }
    for r in filtered:
        fam = str(r.get("family") or "other")
        groups.setdefault(fam, []).append(r)

    invent_run = None
    for name in ("invent_run.json", "last_author_run.json"):
        rp = cdir / name
        if rp.is_file():
            try:
                invent_run = json.loads(rp.read_text(encoding="utf-8"))
            except Exception:  # noqa: BLE001
                invent_run = {"error": "unreadable", "path": str(rp)}
            break

    return {
        "ok": True,
        "dir": str(cdir),
        "count": len(filtered),
        "total_in_manifest": len(enriched),
        "by_seal": by_seal,
        "by_source": by_src,
        "by_family": by_family,
        "by_failure_class": by_failure_class,
        "groups": groups,
        "invent_run": invent_run,
        "role": man.get("role") or "Scenario precursor to Script",
        "generator": man.get("generator"),
        "scenarios": filtered,
        "taxonomy_note": (
            "Failure mode slug = unique registry id (e.g. owner_steal). "
            "Candidate scenario = one trajectory; many scenarios/incidents → one mode. "
            "Not a full FMEA — walking map only. See console Help."
        ),
    }


def _trajectory_from_scenario(parsed: dict[str, Any] | None) -> dict[str, Any]:
    """Human trajectory view: ordered twists + envelopes (not yet a Script)."""
    if not isinstance(parsed, dict):
        return {"steps": [], "goal_state": [], "initial_state": []}
    steps_out: list[dict[str, Any]] = []
    for i, step in enumerate(parsed.get("steps") or []):
        if not isinstance(step, dict):
            continue
        payload = step.get("payload") if isinstance(step.get("payload"), dict) else {}
        steps_out.append({
            "index": i,
            "id": step.get("id") or f"step_{i}",
            "actor": step.get("actor") or "user",
            "maneuver": step.get("maneuver") or "",
            "user_text": payload.get("user_text") or payload.get("message") or "",
            "pin": payload.get("pin") or {},
            "invariants": payload.get("invariants") or [],
            "preconditions": step.get("preconditions") or [],
            "postconditions": step.get("postconditions") or [],
            "blocked_conditions": step.get("blocked_conditions") or [],
        })
    return {
        "scenario_id": parsed.get("scenario_id"),
        "scenario_class": parsed.get("scenario_class"),
        "goal_state": list(parsed.get("goal_state") or []),
        "initial_state": list(parsed.get("initial_state") or []),
        "scope": parsed.get("scope") or {},
        "terminal_states": parsed.get("terminal_states") or {},
        "steps": steps_out,
    }


def _compile_script_view(parsed: dict[str, Any] | None) -> dict[str, Any]:
    """Best-effort Scenario → Script for the console (precursor compile)."""
    if not isinstance(parsed, dict):
        return {"ok": False, "error": "no_scenario", "script": None, "turns": []}
    try:
        from conjecture_behaviour_runner.compile_scenario import (
            compile_scenario_to_script,
        )
        from conjecture_behaviour_runner.experimental.scenario_models import Scenario

        scenario = Scenario.model_validate(parsed)
        script = compile_scenario_to_script(
            scenario,
            profile_id="ci_stub_cognition",
            conversation_id=f"conv_{scenario.scenario_id}",
        )
        turns = []
        for i, t in enumerate(script.turns):
            td = t.to_dict() if hasattr(t, "to_dict") else {}
            turns.append({
                "index": i,
                "user_text": td.get("user_text") or getattr(t, "user_text", ""),
                "actor": td.get("actor") or "user",
                "pin": td.get("pin"),
                "invariants": td.get("invariants") or [],
                "allowed_outcomes": td.get("allowed_outcomes") or [],
                "freeze_key": td.get("freeze_key") or getattr(t, "freeze_key", ""),
            })
        return {
            "ok": True,
            "script_id": script.script_id,
            "description": script.description,
            "conversation_id": script.conversation_id,
            "tags": list(getattr(script, "tags", ()) or ()),
            "turns": turns,
            "script": script.to_dict() if hasattr(script, "to_dict") else None,
            "error": None,
        }
    except Exception as exc:  # noqa: BLE001 — show compile gaps in UI
        # Fallback: build a thin script-shaped view from step payloads
        turns = []
        for i, step in enumerate((parsed or {}).get("steps") or []):
            if not isinstance(step, dict):
                continue
            pl = step.get("payload") if isinstance(step.get("payload"), dict) else {}
            turns.append({
                "index": i,
                "user_text": pl.get("user_text") or step.get("maneuver") or "",
                "actor": step.get("actor") or "user",
                "pin": pl.get("pin"),
                "invariants": pl.get("invariants") or [],
                "allowed_outcomes": pl.get("allowed_outcomes") or [],
                "freeze_key": step.get("id") or f"t{i}",
            })
        return {
            "ok": False,
            "error": str(exc),
            "script_id": parsed.get("scenario_id"),
            "description": "payload-derived turns (full Scenario validate/compile failed)",
            "conversation_id": f"conv_{parsed.get('scenario_id')}",
            "tags": ["payload-fallback"],
            "turns": turns,
            "script": None,
        }


def get_candidate(
    scenario_id: str,
    *,
    candidates_dir: Optional[str | Path] = None,
) -> dict[str, Any]:
    """Load one candidate: trajectory + Scenario YAML + compiled Script view."""
    if not _SAFE_ID.match(scenario_id or ""):
        return {"ok": False, "error": "invalid_scenario_id"}
    cdir = resolve_candidates_dir(candidates_dir)
    if cdir is None:
        return {"ok": False, "error": "no_candidates_dir"}
    # Prefer manifest file name
    man = _load_manifest(cdir)
    file_name = f"{scenario_id}.yaml"
    for row in man.get("scenarios") or []:
        if isinstance(row, dict) and row.get("scenario_id") == scenario_id:
            file_name = str(row.get("file") or file_name)
            meta = row
            break
    else:
        meta = {"scenario_id": scenario_id}

    path = cdir / file_name
    if not path.is_file():
        # try bare id
        alt = cdir / f"{scenario_id}.yaml"
        if alt.is_file():
            path = alt
        else:
            return {"ok": False, "error": "not_found", "scenario_id": scenario_id}

    text = path.read_text(encoding="utf-8")
    parsed: Any = None
    try:
        import yaml  # type: ignore[import-untyped]

        parsed = yaml.safe_load(text)
    except Exception:  # noqa: BLE001
        parsed = None

    scenario_dict = parsed if isinstance(parsed, dict) else None
    trajectory = _trajectory_from_scenario(scenario_dict)
    script_view = _compile_script_view(scenario_dict)

    # Deep links for the local console (hash routes)
    links = {
        "console": f"/#/candidate/{scenario_id}",
        "trajectory": f"/#/candidate/{scenario_id}/trajectory",
        "scenario": f"/#/candidate/{scenario_id}/scenario",
        "script": f"/#/candidate/{scenario_id}/script",
        "api": f"/api/candidates/{scenario_id}",
    }

    meta_out = dict(meta) if isinstance(meta, dict) else {"scenario_id": scenario_id}
    meta_out["family"] = source_family(str(meta_out.get("source") or ""))
    if not meta_out.get("failure_class"):
        scope = (scenario_dict or {}).get("scope") if scenario_dict else None
        meta_out["failure_class"] = failure_class_from_row(
            meta_out, scenario_yaml_scope=scope,
        )

    return {
        "ok": True,
        "scenario_id": scenario_id,
        "meta": meta_out,
        "path": str(path),
        "yaml": text,
        "scenario": scenario_dict,
        "trajectory": trajectory,
        "script_view": script_view,
        "links": links,
        "role": "Scenario precursor to Script",
        "stack": {
            "trajectory": "One multi-turn path (candidate scenario) that stresses a failure class",
            "scenario": "Conjecture Scenario YAML (description + envelopes)",
            "script": "Compiled Conjecture Script (play-back form)",
            "failure_mode": "Taxonomy class (many scenarios may share one mode)",
        },
    }


__all__ = [
    "failure_class_from_row",
    "get_candidate",
    "list_candidates",
    "resolve_candidates_dir",
    "source_family",
]
