"""Load host-authored Conjecture Scenario candidates for the local UI.

Candidates are Scenario YAML (precursor to Script), usually generated by a host
author (``conjecture candidates author`` or host wrapper).

Discovery order:
  1. ``CONJECTURE_CANDIDATES_DIR`` env
  2. Walk cwd parents for ``candidates/scenarios/manifest.json``
  3. Empty list (UI shows how to generate)
"""
from __future__ import annotations

import json
import os
import re
from pathlib import Path
from typing import Any, Optional

_SAFE_ID = re.compile(r"^[A-Za-z0-9._-]{1,160}$")


def resolve_candidates_dir(
    explicit: Optional[str | Path] = None,
) -> Optional[Path]:
    if explicit is not None:
        p = Path(explicit)
        return p if p.is_dir() else None
    env = (os.environ.get("CONJECTURE_CANDIDATES_DIR") or "").strip()
    if env:
        p = Path(env).expanduser()
        if p.is_dir():
            return p
    # Portable layout: any host may put authored scenarios under candidates/scenarios
    cwd = Path.cwd().resolve()
    for base in [cwd, *cwd.parents]:
        p = base / "candidates" / "scenarios"
        if p.is_dir() and (p / "manifest.json").is_file():
            return p
        if base.parent == base:
            break
    return None


def _load_manifest(cdir: Path) -> dict[str, Any]:
    mp = cdir / "manifest.json"
    if not mp.is_file():
        return {"scenarios": [], "generator": None, "role": None}
    try:
        data = json.loads(mp.read_text(encoding="utf-8"))
        return data if isinstance(data, dict) else {"scenarios": []}
    except Exception:  # noqa: BLE001
        return {"scenarios": [], "error": "manifest_unreadable"}


def list_candidates(
    *,
    candidates_dir: Optional[str | Path] = None,
    seal: Optional[str] = None,
    priority: Optional[str] = None,
    source: Optional[str] = None,
    limit: int = 200,
    q: Optional[str] = None,
) -> dict[str, Any]:
    """Return list payload for GET /api/candidates."""
    cdir = resolve_candidates_dir(candidates_dir)
    if cdir is None:
        return {
            "ok": True,
            "dir": None,
            "count": 0,
            "scenarios": [],
            "hint": (
                "No candidate Scenario dir found. Run "
                "`conjecture candidates author --example --out DIR` "
                "(or your host author), then set "
                "CONJECTURE_CANDIDATES_DIR=DIR and re-open this console."
            ),
            "role": "Scenario precursor to Script",
        }
    man = _load_manifest(cdir)
    rows = list(man.get("scenarios") or [])
    if not isinstance(rows, list):
        rows = []

    def _ok(row: dict[str, Any]) -> bool:
        if seal and str(row.get("seal_status") or "") != seal:
            return False
        if priority and str(row.get("priority") or "") != priority:
            return False
        if source and str(row.get("source") or "") != source:
            return False
        if q:
            blob = " ".join(
                str(row.get(k) or "")
                for k in ("scenario_id", "path_id", "source", "seal_status")
            ).lower()
            if q.lower() not in blob:
                return False
        return True

    filtered = [r for r in rows if isinstance(r, dict) and _ok(r)]
    # Prefer open/partial high first (manifest may already be sorted)
    pri = {"high": 0, "medium": 1, "low": 2}
    seal_r = {"open": 0, "partial": 1, "sealed": 2, "regression_check": 3}

    def _key(r: dict[str, Any]) -> tuple:
        return (
            pri.get(str(r.get("priority") or ""), 9),
            seal_r.get(str(r.get("seal_status") or ""), 9),
            str(r.get("scenario_id") or ""),
        )

    filtered = sorted(filtered, key=_key)[: max(0, int(limit))]
    by_seal: dict[str, int] = {}
    by_src: dict[str, int] = {}
    for r in rows:
        if not isinstance(r, dict):
            continue
        s = str(r.get("seal_status") or "?")
        by_seal[s] = by_seal.get(s, 0) + 1
        src = str(r.get("source") or "?")
        by_src[src] = by_src.get(src, 0) + 1

    return {
        "ok": True,
        "dir": str(cdir),
        "count": len(filtered),
        "total_in_manifest": len(rows),
        "by_seal": by_seal,
        "by_source": by_src,
        "role": man.get("role") or "Scenario precursor to Script",
        "generator": man.get("generator"),
        "scenarios": filtered,
    }


def _trajectory_from_scenario(parsed: dict[str, Any] | None) -> dict[str, Any]:
    """Human trajectory view: ordered twists + envelopes (not yet a Script)."""
    if not isinstance(parsed, dict):
        return {"steps": [], "goal_state": [], "initial_state": []}
    steps_out: list[dict[str, Any]] = []
    for i, step in enumerate(parsed.get("steps") or []):
        if not isinstance(step, dict):
            continue
        payload = step.get("payload") if isinstance(step.get("payload"), dict) else {}
        steps_out.append({
            "index": i,
            "id": step.get("id") or f"step_{i}",
            "actor": step.get("actor") or "user",
            "maneuver": step.get("maneuver") or "",
            "user_text": payload.get("user_text") or payload.get("message") or "",
            "pin": payload.get("pin") or {},
            "invariants": payload.get("invariants") or [],
            "preconditions": step.get("preconditions") or [],
            "postconditions": step.get("postconditions") or [],
            "blocked_conditions": step.get("blocked_conditions") or [],
        })
    return {
        "scenario_id": parsed.get("scenario_id"),
        "scenario_class": parsed.get("scenario_class"),
        "goal_state": list(parsed.get("goal_state") or []),
        "initial_state": list(parsed.get("initial_state") or []),
        "scope": parsed.get("scope") or {},
        "terminal_states": parsed.get("terminal_states") or {},
        "steps": steps_out,
    }


def _compile_script_view(parsed: dict[str, Any] | None) -> dict[str, Any]:
    """Best-effort Scenario → Script for the console (precursor compile)."""
    if not isinstance(parsed, dict):
        return {"ok": False, "error": "no_scenario", "script": None, "turns": []}
    try:
        from conjecture_behaviour_runner.compile_scenario import (
            compile_scenario_to_script,
        )
        from conjecture_behaviour_runner.experimental.scenario_models import Scenario

        scenario = Scenario.model_validate(parsed)
        script = compile_scenario_to_script(
            scenario,
            profile_id="ci_stub_cognition",
            conversation_id=f"conv_{scenario.scenario_id}",
        )
        turns = []
        for i, t in enumerate(script.turns):
            td = t.to_dict() if hasattr(t, "to_dict") else {}
            turns.append({
                "index": i,
                "user_text": td.get("user_text") or getattr(t, "user_text", ""),
                "actor": td.get("actor") or "user",
                "pin": td.get("pin"),
                "invariants": td.get("invariants") or [],
                "allowed_outcomes": td.get("allowed_outcomes") or [],
                "freeze_key": td.get("freeze_key") or getattr(t, "freeze_key", ""),
            })
        return {
            "ok": True,
            "script_id": script.script_id,
            "description": script.description,
            "conversation_id": script.conversation_id,
            "tags": list(getattr(script, "tags", ()) or ()),
            "turns": turns,
            "script": script.to_dict() if hasattr(script, "to_dict") else None,
            "error": None,
        }
    except Exception as exc:  # noqa: BLE001 — show compile gaps in UI
        # Fallback: build a thin script-shaped view from step payloads
        turns = []
        for i, step in enumerate((parsed or {}).get("steps") or []):
            if not isinstance(step, dict):
                continue
            pl = step.get("payload") if isinstance(step.get("payload"), dict) else {}
            turns.append({
                "index": i,
                "user_text": pl.get("user_text") or step.get("maneuver") or "",
                "actor": step.get("actor") or "user",
                "pin": pl.get("pin"),
                "invariants": pl.get("invariants") or [],
                "allowed_outcomes": pl.get("allowed_outcomes") or [],
                "freeze_key": step.get("id") or f"t{i}",
            })
        return {
            "ok": False,
            "error": str(exc),
            "script_id": parsed.get("scenario_id"),
            "description": "payload-derived turns (full Scenario validate/compile failed)",
            "conversation_id": f"conv_{parsed.get('scenario_id')}",
            "tags": ["payload-fallback"],
            "turns": turns,
            "script": None,
        }


def get_candidate(
    scenario_id: str,
    *,
    candidates_dir: Optional[str | Path] = None,
) -> dict[str, Any]:
    """Load one candidate: trajectory + Scenario YAML + compiled Script view."""
    if not _SAFE_ID.match(scenario_id or ""):
        return {"ok": False, "error": "invalid_scenario_id"}
    cdir = resolve_candidates_dir(candidates_dir)
    if cdir is None:
        return {"ok": False, "error": "no_candidates_dir"}
    # Prefer manifest file name
    man = _load_manifest(cdir)
    file_name = f"{scenario_id}.yaml"
    for row in man.get("scenarios") or []:
        if isinstance(row, dict) and row.get("scenario_id") == scenario_id:
            file_name = str(row.get("file") or file_name)
            meta = row
            break
    else:
        meta = {"scenario_id": scenario_id}

    path = cdir / file_name
    if not path.is_file():
        # try bare id
        alt = cdir / f"{scenario_id}.yaml"
        if alt.is_file():
            path = alt
        else:
            return {"ok": False, "error": "not_found", "scenario_id": scenario_id}

    text = path.read_text(encoding="utf-8")
    parsed: Any = None
    try:
        import yaml  # type: ignore[import-untyped]

        parsed = yaml.safe_load(text)
    except Exception:  # noqa: BLE001
        parsed = None

    scenario_dict = parsed if isinstance(parsed, dict) else None
    trajectory = _trajectory_from_scenario(scenario_dict)
    script_view = _compile_script_view(scenario_dict)

    # Deep links for the local console (hash routes)
    links = {
        "console": f"/#/candidate/{scenario_id}",
        "trajectory": f"/#/candidate/{scenario_id}/trajectory",
        "scenario": f"/#/candidate/{scenario_id}/scenario",
        "script": f"/#/candidate/{scenario_id}/script",
        "api": f"/api/candidates/{scenario_id}",
    }

    return {
        "ok": True,
        "scenario_id": scenario_id,
        "meta": meta,
        "path": str(path),
        "yaml": text,
        "scenario": scenario_dict,
        "trajectory": trajectory,
        "script_view": script_view,
        "links": links,
        "role": "Scenario precursor to Script",
        "stack": {
            "trajectory": "Authored twists (story of the failure mode)",
            "scenario": "Conjecture Scenario YAML (description + envelopes)",
            "script": "Compiled Conjecture Script (play-back form)",
        },
    }


__all__ = [
    "get_candidate",
    "list_candidates",
    "resolve_candidates_dir",
]
